### ISSUE TITLE
Add Makefile targets and horizon files

### ISSUE THREAD

**Issue by t-fine** [open-horizon-services/web-helloworld-java#2]
Eventually we will want to add the following Makefile targets 
```
publish-service:

publish-pattern:

register-pattern:
```

in addition to the corresponding `service.json` and `pattern.json` files

**Comment by dipesh-rawat** [comment]
@t-fine Could you also assign this issue to me. 
I had a go at making required changes for this issue by comparing with other sample repos. Have created a draft PR #5 with changes. If you could please review the same and let me know if something is missing.

**Comment by t-fine** [comment]
@dipesh-rawat sorry just seeing this, can assign It to you now if you still want to take it on

**Comment by t-fine** [comment]
Your PR looked good! I have gone ahead and merged it. Thanks for contributing!!
